name    'puppet-windows_java'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-windows_java.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Installs Java on the Windows Platform'
description 'Installs Java on the Windows Platform'
project_page 'https://github.com/openstack-hyper-v/puppet-windows_java'
dependency 'joshcooper/powershell'
dependency 'openstack-hyper-v/windows_common'
dependency 'basti1302/windows_path'

